[index]
auto_update_asked = true
last_update = 226142452
[toolchain]
assistant = false
[toolchain.external]
gnat = false
gprbuild = false
[toolchain.use]
gnat = "gnat_native=14.1.3"
gprbuild = "gprbuild=22.0.1"

